version: '3'

services:
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - "9002:9002"
    links:
      - database
  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "5173:5173"
    links:
      - api
